### ISSUE TITLE
보드 페이지 activity

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team3-wannaGoHome#11]
### 이슈 내용:

- activity

**Comment by JunsuLime** [comment]
객체

1. 객체 만들고
2. FlyWayMigration 에 version update
3. 객체 메소드 만들고 테스트

**Comment by JunsuLime** [comment]
// TODO: 2018. 8. 21. 이벤트리스너들 만들고 서비스에서 publish 해주기
// TODO: 2018. 8. 21. Team invite 시 cache 달아주기
// TODO: 2018. 8. 21. 새로운 topic 에 대해 내려주기 
// TODO: 2018. 8. 21. delete subscribe 지우기
// TODO: Notification Pusher Component 를 만들까?

**Comment by songintae** [comment]
1. 이벤트 리스너 상속으로 푸쉬메시지 보내는 로직 공통 처리

2. @MappedSuperclass 사용해서 엔티티 객체에 공통 칼럼 추상화하기

3. 동적 웹소켓 토픽 추가 모든 경우 분석하기

4. 양방향 연결 엔티티들 확인 및 수정

**Comment by JunsuLime** [comment]
topic 등등 여러가지 이번 풀리퀘 네이밍 제대로 변경

**Comment by songintae** [comment]
1. 보드페이지에 체팅이랑 알림 페이지 반반씩 두는거보다 체팅만 두게하고, 알림창으로 다 알림이 오게하고 스크롤시 이전껄 조회하게 하는것이 어떨까?

2. 메시지 내용만 전달하지말고 행동한 시간도 내려주기
