### ISSUE TITLE
위키를 써줘!

### ISSUE THREAD

**Issue by JunsuLime** [wwh-techcamp-2018/team3-wannaGoHome#20]
# 재형

MouseEvent  에 대해 wiki 에 올려줘 `~_~`

# 연

Font Awesome 에 대해 알려줘 ㅎㅎㅎ

# 준수

로그아웃의 Http Method

**Comment by nigayo** [comment]
도와줘 라벨이 있다니 ㅎ 잼있네요.

**Comment by JunsuLime** [comment]
@jhyang12345 웹소켓 설명 써주기
@songintae 로그 파일 관리 써주기
