### ISSUE TITLE
공통 상단바 알림 기능

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team3-wannaGoHome#4]
### 이슈 내용:

알림 기능 구현

**Comment by JunsuLime** [comment]
<img width="842" alt="2018-08-24 3 18 03" src="https://user-images.githubusercontent.com/17852124/44544138-6645be80-a74c-11e8-928c-7eb370ad05e1.png">

**Comment by JunsuLime** [comment]
![image](https://user-images.githubusercontent.com/17852124/44567829-2532c600-a7af-11e8-86f0-adedbd42aed9.png)
