### ISSUE TITLE
로그인 페이지 이슈사항

### ISSUE THREAD

**Issue by JunsuLime** [wwh-techcamp-2018/team3-wannaGoHome#56]
### 이슈 내용:

로그인시 콘솔에 에러가 찍힘

### 이슈 발생 이유:

이건 확인해봐야함

### 하고싶은 말:

없음

**Comment by JunsuLime** [comment]
두번째는

로그인 이후에는 로그인 페이지 못가게 ㅇㅇ 그리고 로그아웃 버튼 넣기

**Comment by nigayo** [comment]
버그수정 라벨의 색깔이 아름답네요.

**Comment by JunsuLime** [comment]
중복로그인 막기

**Comment by JunsuLime** [comment]
spell check 막기
