### ISSUE TITLE
메인 페이지 사이드바 

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team3-wannaGoHome#6]
### 이슈 내용:

- 사이드바
		- 팀 만들기/ 모든 팀 보여주기 등

**Comment by kimyeon0331** [comment]
<img width="1438" alt="2018-08-24 1 16 45" src="https://user-images.githubusercontent.com/19780879/44565447-24943280-a7a3-11e8-9922-89a5b072708e.png">
<img width="310" alt="2018-08-24 1 39 04" src="https://user-images.githubusercontent.com/19780879/44565450-2c53d700-a7a3-11e8-8af9-db33618bd53d.png">

**Comment by kimyeon0331** [comment]
<img width="325" alt="2018-08-24 1 41 10" src="https://user-images.githubusercontent.com/19780879/44565507-63c28380-a7a3-11e8-8c0b-f2914af8b201.png">
