### ISSUE TITLE
데모에서 발견한 에러는 여기 작성해주세요!

### ISSUE THREAD

**Issue by kimyeon0331** [wwh-techcamp-2018/team3-wannaGoHome#79]
버그 발생 상황 및 버그 내용을 상세하게 적어주시면 감사하겠습니다@_@

**Comment by jhyang12345** [comment]
리스트에 card 추가를 계속하면 스크롤이 생겨야할 것 같은데 스크롤이 안되서 카드 추가가 안됩니다ㅠㅠ

**Comment by jhyang12345** [comment]
다른 보드로 이동이 안되요!!

**Comment by ffaass** [comment]
리스트 만들 때 이름이 너무 길면 Add List가 사라져요 ㅠㅠ

**Comment by DongHeeYun** [comment]
스웨거 ui 정리해 주세요

**Comment by minsungryu** [comment]
가입하고 로그인하니까 알람이 없는데도 딸랑거려요~

**Comment by minsungryu** [comment]
팀 추가하고 또 추가할 때 이전에 떴던 에러 메시지가 떠요

**Comment by mindock** [comment]
<img width="1440" alt="2018-08-24 5 18 48" src="https://user-images.githubusercontent.com/32254667/44573525-d80c1f80-a7c1-11e8-99fa-ce3beec09bff.png">
리스트 제목을 길게 넣으니깐 리스트 추가하는 버튼이 사라졌어요
